### ISSUE TITLE
Add system test for NI-DCPower that uses channel expansion

### ISSUE THREAD

**Issue by ni-erikcrank** [ni/nitsm-python#118]
There are two system tests for NI-DCPower: test_nidcpower_legacy and test_nidcpower. The latter is disabled with a pytest.mark.skip decorator. This test needs to be updated and enabled now that NI-DCPower supports channel expansion.

**Comment by smooresni** [comment]
#119 suggests removing legacy dc power support.  should we also remove the legacy tests?

**Comment by ni-erikcrank** [comment]
If we remove legacy support then we have to remove the legacy tests. This is my preference (instead of deprecation).

**Comment by smooresni** [comment]
Resolved in #143 
FYI @ni-erikcrank
