### ISSUE TITLE
Remove support for legacy NI-DCPower methods

### ISSUE THREAD

**Issue by ni-erikcrank** [ni/nitsm-python#119]
We want customers to use the new channel-expansion versions of the NI-DCPower methods.

Remove get_all_nidcpower_instrument_names (replaced by get_all_nidcpower_resource_strings).
Remove set_nidcpower_session (replaced by set_nidcpower_session_with_resource_string).

**Comment by smooresni** [comment]
Remove or deprecate?

**Comment by ni-erikcrank** [comment]
I prefer to remove unless there is a good reason to keep.
