### ISSUE TITLE
Remove control_relays and apply_relay_configuration methods because they are not supported in Python

### ISSUE THREAD

**Issue by ni-erikcrank** [ni/nitsm-python#120]
These two TSM methods call directly in the switch sessions associated with the relays, but because these switch sessions are created in the external Python process, those calls will fail when TSM attempts to make those calls within the TestStand process. TSM would need special code to address this problem for python like it does for LabVIEW. For now, we should just remove these methods from the Python API.

**Comment by smooresni** [comment]
Add to known limitations in README.md

**Comment by ni-erikcrank** [comment]
I was incorrect in my assessment of support for these relay methods in python. In fact, because the methods call directly to the switch API using the switch sessions created in python and do not rely on TSM to perform the relay actions, these methods should work correctly. What won't work is the Set Relays step if sessions were created in Python.

Thus, I'm going to close this issue.
